"use client";
import { useState } from "react";
import { AdminFinanceShell } from "@/features/admin/components/admin-finance-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/utils";

type Investor = { profile: { full_name: string | null; email: string }; deposits: Array<{ id: string; amount: number; status: string; reference: string | null }>; allocations: Array<{ id: string; amount: number; status: string; investment_cycles: { funds: { name: string } } }> };
export function AdminInvestorCorrections() {
  const [email, setEmail] = useState(""); const [data, setData] = useState<Investor | null>(null); const [reason, setReason] = useState(""); const [amounts, setAmounts] = useState<Record<string, string>>({}); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function search() { setBusy(true); setMessage(null); try { const r = await fetch(`/api/admin/investor-corrections?email=${encodeURIComponent(email)}`); const j = await r.json(); if (!r.ok) throw new Error(j.error); setData(j.investor); if (!j.investor) setMessage("No investor found."); } catch (e) { setMessage(e instanceof Error ? e.message : "Search failed"); } finally { setBusy(false); } }
  async function save(kind: "deposit" | "investment", id: string) { const amount = Number(amounts[id]); if (!reason.trim() || !Number.isFinite(amount)) { setMessage("Enter a valid amount and correction reason."); return; } setBusy(true); try { const r = await fetch("/api/admin/investor-corrections", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, id, amount, reason }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setMessage("Correction saved and recorded in the admin audit log."); await search(); } catch (e) { setMessage(e instanceof Error ? e.message : "Correction failed"); } finally { setBusy(false); } }
  const row = (kind: "deposit" | "investment", item: { id: string; amount: number; status: string; label: string }) => <div key={item.id} className="grid gap-3 rounded-lg border p-4 md:grid-cols-[1fr_130px_150px]"><div><p className="font-medium text-navy-950">{item.label}</p><p className="text-xs text-navy-500">{item.status} · current {formatCurrency(item.amount)}</p></div><input className="rounded-md border px-3 py-2 text-sm" type="number" min="0.01" step="0.01" placeholder={String(item.amount)} value={amounts[item.id] ?? ""} onChange={(e) => setAmounts((v) => ({ ...v, [item.id]: e.target.value }))}/><Button disabled={busy} onClick={() => void save(kind, item.id)}>Save correction</Button></div>;
  return <AdminFinanceShell title="Investor Financial Corrections" description="Correct deposits or pool investments before profit distribution. Every change is audit logged and immediately becomes the calculation source of truth."><Card><CardHeader><CardTitle className="text-base">Find investor</CardTitle></CardHeader><CardContent className="flex gap-3"><input className="min-w-0 flex-1 rounded-md border px-3 py-2 text-sm" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="investor@email.com"/><Button disabled={busy} onClick={() => void search()}>Search</Button></CardContent></Card>{data && <><Card><CardHeader><CardTitle className="text-base">{data.profile.full_name || "Investor"} · {data.profile.email}</CardTitle></CardHeader><CardContent><textarea className="w-full rounded-md border p-3 text-sm" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Required admin-only correction reason" rows={3}/></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Deposits</CardTitle></CardHeader><CardContent className="space-y-3">{data.deposits.map((d) => row("deposit", { ...d, label: d.reference || "Deposit" }))}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Pool investments</CardTitle></CardHeader><CardContent className="space-y-3">{data.allocations.map((a) => row("investment", { ...a, label: a.investment_cycles.funds.name }))}</CardContent></Card></>}{message && <p className="text-sm text-navy-600">{message}</p>}</AdminFinanceShell>;
}
