import { DEFAULT_FUND_ID, DEFAULT_FUND_NAME } from "@/constants/funds";
import { USER_ROLES } from "@/constants/roles";
import type {
  AdminAnnouncement,
  AdminDashboardStats,
  AdminDepositRequest,
  AdminFund,
  AdminInvestor,
  AdminTestimonial,
  AdminTrade,
  AdminTransaction,
  AdminTrendPoint,
  AdminWithdrawalRequest,
  AuditLogEntry,
  DailyFundSnapshot,
  PlatformSetting,
} from "@/features/admin/types";

export const mockAdminDashboardStats: AdminDashboardStats = {
  totalPoolValue: 2847500,
  activeInvestors: 127,
  pendingDeposits: 4,
  pendingWithdrawals: 2,
  dailyRoi: 0.42,
  monthlyRoi: 8.74,
  assetsUnderManagement: 3125000,
  totalDeposits: 3125000,
  totalWithdrawals: 277500,
  activeTrades: 1,
  closedTrades: 341,
  winRate: 68.4,
};

function generateTrend(days: number, base: number, variance: number): AdminTrendPoint[] {
  const points: AdminTrendPoint[] = [];
  const now = new Date();
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    points.push({
      date: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
      value: Math.round(base + (Math.random() - 0.4) * variance),
    });
  }
  return points;
}

export const mockPoolGrowthTrend = generateTrend(30, 2700000, 200000);
export const mockDepositTrend = generateTrend(30, 45000, 35000);
export const mockWithdrawalTrend = generateTrend(30, 12000, 15000);
export const mockInvestmentTrend = generateTrend(30, 2800000, 180000);
export const mockDailyRoiTrend = generateTrend(30, 0.3, 1.2).map((p) => ({
  ...p,
  value: Number((p.value / 100).toFixed(2)),
}));

export const mockAdminFunds: AdminFund[] = [
  {
    id: DEFAULT_FUND_ID,
    name: DEFAULT_FUND_NAME,
    slug: "ryvonx-main-pool",
    description: "Flagship professionally managed trading pool.",
    status: "active",
    isDefault: true,
    minInvestment: 100,
    maxInvestment: null,
    poolValue: 2847500,
    assetsUnderManagement: 3125000,
    activeInvestors: 127,
    currentRoi: 47.32,
    createdAt: "2025-01-01T00:00:00Z",
    poolDescription: "Flagship professionally managed trading pool.",
    tradingPair: "Multi-pair",
    poolDurationDays: 90,
    targetCapital: 1000000,
    profitTargetPct: 15,
    targetInvestors: 100,
    returnTiers: [
      { minAmount: 100, maxAmount: 999, returnPct: 8 },
      { minAmount: 1000, maxAmount: 4999, returnPct: 12 },
      { minAmount: 5000, maxAmount: null, returnPct: 18 },
    ],
    isInviteOnly: false,
    currentCapital: 2847500,
    cardBackgroundColor: "#0f1623",
    poolManagerName: null,
    poolManagerIconUrl: null,
    canDelete: false,
    isMarketplaceListed: true,
    featured: true,
    tagline: "Official RyvonX platform-managed trading pool",
    categories: ["balanced", "multi_asset"],
    securityRating: "balanced",
    aggressivenessLevel: "moderate",
    poolHealth: "healthy",
    capacityStatus: "open",
    ryvonxRating: 4.5,
    suggestedInvestment: 100,
    riskSummary: null,
    adminComments: null,
    coverImageUrl: null,
    logoUrl: null,
    lifecycleStatus: "live",
    maxAum: 1000000,
    maxInvestorsCap: 100,
    displayActiveInvestors: 0,
  },
];

export const mockAdminDeposits: AdminDepositRequest[] = [
  {
    id: "dep-001",
    investorId: "inv-001",
    investorName: "Michael R.",
    investorEmail: "michael.r@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 25000,
    paymentMethod: "Bank Transfer",
    reference: "TXN-20260714-001",
    paymentProof: "/proofs/dep-001.pdf",
    notes: "Additional capital allocation",
    adminNotes: null,
    status: "pending",
    submittedAt: "2026-07-14T10:30:00Z",
    processedAt: null,
    approvedBy: null,
  },
  {
    id: "dep-002",
    investorId: "inv-002",
    investorName: "Sarah K.",
    investorEmail: "sarah.k@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 10000,
    paymentMethod: "Wire Transfer",
    reference: "TXN-20260714-002",
    paymentProof: "/proofs/dep-002.pdf",
    notes: null,
    adminNotes: null,
    status: "pending",
    submittedAt: "2026-07-14T08:15:00Z",
    processedAt: null,
    approvedBy: null,
  },
  {
    id: "dep-003",
    investorId: "inv-003",
    investorName: "James T.",
    investorEmail: "james.t@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 50000,
    paymentMethod: "Bank Transfer",
    reference: "TXN-20260713-001",
    paymentProof: "/proofs/dep-003.pdf",
    notes: "Quarterly top-up",
    adminNotes: "Verified with bank statement",
    status: "approved",
    submittedAt: "2026-07-13T16:45:00Z",
    processedAt: "2026-07-13T18:00:00Z",
    approvedBy: "Super Admin",
  },
  {
    id: "dep-004",
    investorId: "inv-004",
    investorName: "Emma L.",
    investorEmail: "emma.l@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 5000,
    paymentMethod: "ACH",
    reference: null,
    paymentProof: null,
    notes: "First deposit",
    adminNotes: "Missing payment proof",
    status: "pending",
    submittedAt: "2026-07-13T11:20:00Z",
    processedAt: null,
    approvedBy: null,
  },
];

export const mockAdminWithdrawals: AdminWithdrawalRequest[] = [
  {
    id: "wd-001",
    investorId: "inv-005",
    investorName: "Robert H.",
    investorEmail: "robert.h@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 8000,
    withdrawableBalance: 42000,
    destination: "Chase ****4821",
    notes: "Partial withdrawal",
    adminNotes: null,
    status: "pending",
    submittedAt: "2026-07-14T09:00:00Z",
    processedAt: null,
    approvedBy: null,
  },
  {
    id: "wd-002",
    investorId: "inv-006",
    investorName: "Anna P.",
    investorEmail: "anna.p@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 12000,
    withdrawableBalance: 85000,
    destination: "Wells Fargo ****9034",
    notes: null,
    adminNotes: null,
    status: "pending",
    submittedAt: "2026-07-13T15:30:00Z",
    processedAt: null,
    approvedBy: null,
  },
  {
    id: "wd-003",
    investorId: "inv-007",
    investorName: "Chris B.",
    investorEmail: "chris.b@email.com",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    amount: 3500,
    withdrawableBalance: 22000,
    destination: "Bank of America ****7712",
    notes: "Emergency funds",
    adminNotes: "Processed same day",
    status: "completed",
    submittedAt: "2026-07-12T17:00:00Z",
    processedAt: "2026-07-13T10:00:00Z",
    approvedBy: "Super Admin",
  },
];

export const mockAdminInvestors: AdminInvestor[] = [
  {
    profile: {
      id: "inv-001",
      email: "michael.r@email.com",
      fullName: "Michael R.",
      avatarUrl: null,
      role: USER_ROLES.INVESTOR,
      phone: "+1 555-0101",
      isActive: true,
      emailVerified: true,
      createdAt: "2025-03-15T00:00:00Z",
      updatedAt: "2026-07-14T10:30:00Z",
    },
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    accountStatus: "active",
    totalInvested: 125000,
    currentValue: 148200,
    ownershipPercentage: 4.38,
    totalDeposits: 125000,
    totalWithdrawals: 0,
    roi: 18.56,
    showActivityPublicly: true,
    lastActiveAt: "2026-07-14T10:30:00Z",
  },
  {
    profile: {
      id: "inv-002",
      email: "sarah.k@email.com",
      fullName: "Sarah K.",
      avatarUrl: null,
      role: USER_ROLES.INVESTOR,
      phone: "+1 555-0102",
      isActive: true,
      emailVerified: true,
      createdAt: "2025-06-20T00:00:00Z",
      updatedAt: "2026-07-14T08:15:00Z",
    },
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    accountStatus: "active",
    totalInvested: 75000,
    currentValue: 89250,
    ownershipPercentage: 2.64,
    totalDeposits: 75000,
    totalWithdrawals: 5000,
    roi: 19.0,
    showActivityPublicly: true,
    lastActiveAt: "2026-07-14T08:15:00Z",
  },
  {
    profile: {
      id: "inv-008",
      email: "thomas.a@email.com",
      fullName: "Thomas A.",
      avatarUrl: null,
      role: USER_ROLES.INVESTOR,
      phone: null,
      isActive: false,
      emailVerified: true,
      createdAt: "2025-01-10T00:00:00Z",
      updatedAt: "2026-06-01T00:00:00Z",
    },
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    accountStatus: "suspended",
    totalInvested: 30000,
    currentValue: 28500,
    ownershipPercentage: 1.05,
    totalDeposits: 30000,
    totalWithdrawals: 0,
    roi: -5.0,
    showActivityPublicly: false,
    lastActiveAt: "2026-05-28T14:00:00Z",
  },
];

export const mockAdminTrades: AdminTrade[] = [
  {
    id: "trade-001",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    symbol: "BTC/USD",
    direction: "long",
    entryPrice: 64200,
    exitPrice: 66850,
    stopLoss: 62800,
    takeProfit: 68000,
    quantity: 2.5,
    pnl: 6625,
    pnlPercentage: 4.13,
    status: "closed",
    openedAt: "2026-07-10T08:00:00Z",
    closedAt: "2026-07-12T16:30:00Z",
    notes: "Breakout above resistance",
    publishedAt: "2026-07-12T17:00:00Z",
    screenshotUrl: null,
  },
  {
    id: "trade-002",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    symbol: "ETH/USD",
    direction: "short",
    entryPrice: 3450,
    exitPrice: 3310,
    stopLoss: 3520,
    takeProfit: 3250,
    quantity: 15,
    pnl: 2100,
    pnlPercentage: 4.06,
    status: "closed",
    openedAt: "2026-07-08T10:00:00Z",
    closedAt: "2026-07-09T14:00:00Z",
    notes: "Pullback from overbought",
    publishedAt: "2026-07-09T15:00:00Z",
    screenshotUrl: null,
  },
  {
    id: "trade-003",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    symbol: "SOL/USD",
    direction: "long",
    entryPrice: 178.5,
    exitPrice: null,
    stopLoss: 170,
    takeProfit: 195,
    quantity: 500,
    pnl: null,
    pnlPercentage: null,
    status: "open",
    openedAt: "2026-07-14T06:00:00Z",
    closedAt: null,
    notes: "Momentum play",
    publishedAt: null,
    screenshotUrl: null,
  },
];

export const mockDailySnapshots: DailyFundSnapshot[] = [
  {
    id: "snap-001",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    date: "2026-07-13",
    openingPoolValue: 2835000,
    closingPoolValue: 2847500,
    dailyRoi: 0.44,
    dailyProfitLoss: 12500,
    tradesCount: 3,
    winningTrades: 2,
    losingTrades: 1,
    winRate: 66.7,
    depositsReceived: 50000,
    withdrawalsProcessed: 0,
    activeInvestors: 127,
    assetsUnderManagement: 3125000,
    managerNotes: "Strong day. BTC breakout performed well.",
    isLocked: true,
    createdAt: "2026-07-13T22:00:00Z",
  },
  {
    id: "snap-002",
    fundId: DEFAULT_FUND_ID,
    fundName: DEFAULT_FUND_NAME,
    date: "2026-07-12",
    openingPoolValue: 2828000,
    closingPoolValue: 2835000,
    dailyRoi: 0.25,
    dailyProfitLoss: 7000,
    tradesCount: 2,
    winningTrades: 2,
    losingTrades: 0,
    winRate: 100,
    depositsReceived: 15000,
    withdrawalsProcessed: 3500,
    activeInvestors: 126,
    assetsUnderManagement: 3070000,
    managerNotes: null,
    isLocked: true,
    createdAt: "2026-07-12T22:00:00Z",
  },
];

export const mockAdminTransactions: AdminTransaction[] = [
  { id: "txn-001", investorName: "Michael R.", fundName: DEFAULT_FUND_NAME, type: "deposit", amount: 25000, status: "pending", reference: "TXN-20260714-001", createdAt: "2026-07-14T10:30:00Z", processedAt: null },
  { id: "txn-002", investorName: "Robert H.", fundName: DEFAULT_FUND_NAME, type: "withdrawal", amount: 8000, status: "pending", reference: null, createdAt: "2026-07-14T09:00:00Z", processedAt: null },
  { id: "txn-003", investorName: "James T.", fundName: DEFAULT_FUND_NAME, type: "deposit", amount: 50000, status: "completed", reference: "TXN-20260713-001", createdAt: "2026-07-13T16:45:00Z", processedAt: "2026-07-13T18:00:00Z" },
  { id: "txn-004", investorName: "Chris B.", fundName: DEFAULT_FUND_NAME, type: "withdrawal", amount: 3500, status: "completed", reference: null, createdAt: "2026-07-12T17:00:00Z", processedAt: "2026-07-13T10:00:00Z" },
  { id: "txn-005", investorName: "Admin", fundName: DEFAULT_FUND_NAME, type: "adjustment", amount: 500, status: "completed", reference: "ADJ-001", createdAt: "2026-07-11T12:00:00Z", processedAt: "2026-07-11T12:00:00Z" },
];

export const mockAdminAnnouncements: AdminAnnouncement[] = [
  {
    id: "ann-001",
    title: "July Performance Update",
    content: "The fund delivered strong returns this month driven by crypto momentum plays.",
    fundName: DEFAULT_FUND_NAME,
    isPublished: true,
    publishedAt: "2026-07-01T10:00:00Z",
    createdAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "ann-002",
    title: "Scheduled Maintenance",
    content: "Platform maintenance scheduled for July 20, 2026 from 2–4 AM UTC.",
    fundName: DEFAULT_FUND_NAME,
    isPublished: false,
    publishedAt: null,
    createdAt: "2026-07-10T14:00:00Z",
  },
];

export const mockAdminTestimonials: AdminTestimonial[] = [
  { id: "tm-001", name: "Alexander M.", role: "Private Investor", content: "The transparency sold me.", rating: 5, returnRate: 18.4, isPublished: true },
  { id: "tm-002", name: "Priya S.", role: "Portfolio Manager", content: "Professional approach and clear reporting.", rating: 5, returnRate: 24.1, isPublished: true },
  { id: "tm-003", name: "Draft User", role: "Entrepreneur", content: "Pending review testimonial.", rating: 4, returnRate: null, isPublished: false },
];

export const mockAuditLogs: AuditLogEntry[] = [
  { id: "log-001", actorName: "Super Admin", action: "deposit_approved", entityType: "transaction", entityId: "dep-003", summary: "Approved deposit of $50,000 for James T.", createdAt: "2026-07-13T18:00:00Z" },
  { id: "log-002", actorName: "Super Admin", action: "trade_published", entityType: "trade", entityId: "trade-001", summary: "Published BTC/USD long trade to journal", createdAt: "2026-07-12T17:00:00Z" },
  { id: "log-003", actorName: "Super Admin", action: "snapshot_closed", entityType: "daily_snapshot", entityId: "snap-001", summary: "Closed trading day for 2026-07-13", createdAt: "2026-07-13T22:00:00Z" },
  { id: "log-004", actorName: "Super Admin", action: "investor_suspended", entityType: "profile", entityId: "inv-008", summary: "Suspended account for Thomas A.", createdAt: "2026-06-01T09:00:00Z" },
  { id: "log-005", actorName: "Super Admin", action: "settings_updated", entityType: "platform_settings", entityId: null, summary: "Updated support email configuration", createdAt: "2026-05-15T11:00:00Z" },
];

export const mockPlatformSettings: PlatformSetting[] = [
  { key: "company_name", label: "Company Name", value: "Ryvonx", group: "Branding" },
  { key: "support_email", label: "Support Email", value: "hello@ryvonx.com", group: "Contact" },
  { key: "min_investment", label: "Minimum Investment", value: "100", group: "Investment" },
  { key: "max_investment", label: "Maximum Investment", value: "", group: "Investment" },
  { key: "currency", label: "Currency", value: "USD", group: "Regional" },
  { key: "timezone", label: "Timezone", value: "America/New_York", group: "Regional" },
  { key: "default_fund_id", label: "Default Fund", value: DEFAULT_FUND_ID, group: "Funds" },
];
