import { ROUTES } from "@/constants/routes";
import { registerRoute, REGISTRATION_INTENTS } from "@/constants/registration";
import { APP_NAME } from "@/constants/routes";
import type { LandingPageContent } from "@/domain/landing-page/types";

export const DEFAULT_LANDING_PAGE_CONTENT: LandingPageContent = {
  hero: {
    badge: "Transparent Pool Trading Fund",
    heading: "Where Smart Investors Meet Great Traders.",
    subheading: "",
    description:
      "Discover transparent investment pools managed by verified trading professionals.",
    primaryButtonText: "Explore Pools",
    primaryButtonLink: ROUTES.marketplace,
    secondaryButtonText: "Create Pool",
    secondaryButtonLink: registerRoute(REGISTRATION_INTENTS.CREATE_POOL),
    backgroundImageUrl: "/images/hero-cover.png",
    illustrationImageUrl: "",
    videoUrl: "",
    trustBanner: "",
    showTrustTicker: true,
    floatingStats: [],
  },
  heroStats: [
    { id: "hs1", title: "Total Pool Value", mode: "automatic", automaticKey: "total_pool_value", icon: "TrendingUp", valueFormat: "currency" },
    { id: "hs2", title: "Active Investors", mode: "automatic", automaticKey: "active_investors", icon: "Users", valueFormat: "number" },
    { id: "hs3", title: "Today's ROI", mode: "automatic", automaticKey: "daily_roi", icon: "BarChart3", changeType: "positive", valueFormat: "percentage" },
    { id: "hs4", title: "Monthly ROI", mode: "automatic", automaticKey: "monthly_roi", icon: "Activity", changeType: "positive", valueFormat: "percentage" },
    { id: "hs5", title: "Win Rate", mode: "automatic", automaticKey: "win_rate", icon: "Target", valueFormat: "percentage" },
    { id: "hs6", title: "Closed Trades", mode: "automatic", automaticKey: "closed_trades", icon: "BarChart3", valueFormat: "number" },
  ],
  statistics: [
    { id: "s1", title: "Verified Pool Managers", mode: "automatic", automaticKey: "verified_pool_managers", icon: "Shield", valueFormat: "number" },
    { id: "s2", title: "Capital Managed", mode: "automatic", automaticKey: "capital_managed", icon: "Wallet", valueFormat: "currency" },
    { id: "s3", title: "Active Investors", mode: "automatic", automaticKey: "active_investors", icon: "Users", valueFormat: "number" },
    { id: "s4", title: "Trading Pools", mode: "automatic", automaticKey: "trading_pools", icon: "BarChart3", valueFormat: "number" },
    { id: "s5", title: "Supported Brokers", mode: "automatic", automaticKey: "supported_brokers", icon: "Landmark", valueFormat: "number" },
    { id: "s6", title: "Countries", mode: "automatic", automaticKey: "countries", icon: "Target", valueFormat: "number" },
  ],
  brokers: [
    { id: "b1", name: "Pepperstone", logoUrl: "/images/brokers/pepperstone.svg", sortOrder: 0, isPrimary: true, isEnabled: true },
    { id: "b2", name: "IC Markets", logoUrl: "/images/brokers/icmarkets.svg", sortOrder: 1, isPrimary: false, isEnabled: true },
    { id: "b3", name: "XM", logoUrl: "/images/brokers/xm.svg", sortOrder: 2, isPrimary: false, isEnabled: true },
    { id: "b4", name: "Exness", logoUrl: "/images/brokers/exness.svg", sortOrder: 3, isPrimary: false, isEnabled: true },
    { id: "b5", name: "FP Markets", logoUrl: "/images/brokers/fpmarkets.svg", sortOrder: 4, isPrimary: false, isEnabled: true },
    { id: "b6", name: "OANDA", logoUrl: "/images/brokers/oanda.svg", sortOrder: 5, isPrimary: false, isEnabled: true },
  ],
  settings: {
    enableSectionAnimations: true,
    brokerSliderAutoScroll: true,
    featuredManagersAutoRotate: true,
  },
  riskWarning: {
    enabled: true,
    text: "Risk Warning: Trading leveraged products involves a high level of risk and may result in the loss of your invested capital. Make sure you understand the risks involved before trading.",
  },
  copyTradingEducation: {
    enabled: true,
    intro: {
      enabled: true,
      eyebrow: "COPY TRADING WITH RYVONX",
      heading: "A simpler way to participate in the financial markets.",
      description:
        "If you want to open a Copy Trading account, simply click on the button below. If you want to learn more about Copy Trading, explore the sections below.",
      ctaEnabled: true,
      ctaLabel: "START COPYING NOW",
      ctaHref: ROUTES.marketplace,
    },
    sections: [
      {
        id: "what-is-copy-trading",
        enabled: true,
        order: 1,
        displayNumber: "01",
        title: "What is Copy Trading, and How Does It Work?",
        body: "Copy trading lets you choose a trader and allocate capital to follow that trader's strategy. Your account reflects the results applicable to your allocation while the strategy is being copied.\n\nTrading performance can include both profits and losses. Choosing to copy a trader does not guarantee a positive result.",
        ctaEnabled: true,
        ctaLabel: "Explore Traders",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "how-copy-trading-works",
        enabled: true,
        order: 2,
        displayNumber: "02",
        title: "How Copy Trading Works on RyvonX",
        body: "Create your account and fund it, then explore verified traders in the Marketplace. Review each trader's profile, strategy, risk information, and available performance history before choosing who to copy.\n\nAfter you choose an amount, your capital is allocated to the applicable trading period. You can then monitor the copied trader and the results connected to your allocation from your RyvonX dashboard.",
        ctaEnabled: true,
        ctaLabel: "Start Copying",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "advantages",
        enabled: true,
        order: 3,
        displayNumber: "03",
        title: "Advantages of Copy Trading",
        body: "Copy trading can provide access to experienced traders, make strategies easier to compare, and reduce the need to execute every trade personally. RyvonX also brings trader information and performance monitoring into one place.\n\nSome users may choose different traders to diversify their exposure. These are potential benefits, not guarantees of profit or protection from loss.",
        ctaEnabled: true,
        ctaLabel: "Explore Verified Traders",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "capital-allocation",
        enabled: true,
        order: 4,
        displayNumber: "04",
        title: "How Capital Allocation Works",
        body: "You choose how much available capital to allocate when you copy an eligible trader. That allocation represents your participation with the trader during the applicable trading period.\n\nThe Marketplace and trader profile show the information available for the current opportunity so you can review it before confirming your allocation.",
        ctaEnabled: false,
        ctaLabel: "",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "profits-and-losses",
        enabled: true,
        order: 5,
        displayNumber: "05",
        title: "How Profits and Losses Work",
        body: "Results are applied according to each copier's applicable allocation and the existing profit-split terms for that participation. A copier does not receive the trader's entire result.\n\nProfitable trading can increase copying capital, while losses can reduce it. The same trading strategy may produce different outcomes over time, and no result is guaranteed.",
        ctaEnabled: true,
        ctaLabel: "View Traders",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "risks",
        enabled: true,
        order: 6,
        displayNumber: "06",
        title: "Risks and Considerations",
        body: "All trading involves risk, and losses are possible. Past performance does not guarantee future results.\n\nReview a trader's strategy, historical performance, trading approach, and risk information carefully. Only allocate capital that is consistent with your own circumstances and risk tolerance.",
        ctaEnabled: false,
        ctaLabel: "",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "getting-started",
        enabled: true,
        order: 7,
        displayNumber: "07",
        title: "How to Get Started with Copy Trading",
        body: "1. Create your RyvonX account.\n2. Fund your account.\n3. Explore verified traders.\n4. Review trader and strategy information.\n5. Choose an allocation.\n6. Start copying.\n7. Monitor performance from your dashboard.",
        ctaEnabled: true,
        ctaLabel: "Get Started",
        ctaHref: registerRoute(REGISTRATION_INTENTS.JOIN_POOL),
      },
      {
        id: "stop-copying",
        enabled: true,
        order: 8,
        displayNumber: "08",
        title: "Can I Stop Copying?",
        body: "Yes. If you stop before your allocated capital enters active trading, the applicable capital can be returned according to the existing platform process.\n\nIf your capital is already participating in active trading, the request is recorded and takes effect through the current settlement process after the trader closes the applicable trades. Active trading capital is not returned instantly.",
        ctaEnabled: false,
        ctaLabel: "",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "choosing-a-trader",
        enabled: true,
        order: 9,
        displayNumber: "09",
        title: "Choosing a Trader",
        body: "Compare the trader's strategy, historical performance, risk, trading approach, and relevant profile information. Consider whether the strategy matches your own objectives and tolerance for loss.\n\nHistorical performance can help you evaluate a trader, but it does not guarantee future results.",
        ctaEnabled: true,
        ctaLabel: "Browse Marketplace",
        ctaHref: ROUTES.marketplace,
      },
      {
        id: "frequently-asked-questions",
        enabled: true,
        order: 10,
        displayNumber: "10",
        title: "Frequently Asked Questions",
        body: "Clear answers to common questions about copying traders on RyvonX.",
        ctaEnabled: false,
        ctaLabel: "",
        ctaHref: ROUTES.marketplace,
      },
    ],
    faqs: [
      {
        id: "faq-what-is-copy-trading",
        enabled: true,
        order: 1,
        question: "What is copy trading?",
        answer: "Copy trading lets you allocate capital to follow a selected trader's strategy, with results reflected according to your applicable allocation.",
      },
      {
        id: "faq-allocation",
        enabled: true,
        order: 2,
        question: "Do I choose how much capital to allocate?",
        answer: "Yes. You choose an eligible amount from your available funding balance before confirming that you want to copy a trader.",
      },
      {
        id: "faq-losses",
        enabled: true,
        order: 3,
        question: "Can copy trading lose money?",
        answer: "Yes. Trading can produce profits or losses, and past performance does not guarantee future results.",
      },
      {
        id: "faq-choose-trader",
        enabled: true,
        order: 4,
        question: "How do I choose a trader?",
        answer: "Review the trader's strategy, performance history, risk information, trading approach, and profile before deciding.",
      },
      {
        id: "faq-stop-copying",
        enabled: true,
        order: 5,
        question: "Can I stop copying?",
        answer: "Yes. Available capital can be returned through the existing process. Capital already in active trading is settled after the applicable trades are closed.",
      },
      {
        id: "faq-monitor",
        enabled: true,
        order: 6,
        question: "Where can I monitor performance?",
        answer: "Your RyvonX dashboard shows the traders you copy, your copying capital, and the available performance activity connected to your account.",
      },
      {
        id: "faq-past-performance",
        enabled: true,
        order: 7,
        question: "Does past performance guarantee future results?",
        answer: "No. Historical performance is informational and does not guarantee future profits or prevent losses.",
      },
    ],
  },
  contact: {
    companyName: APP_NAME,
    supportEmail: "hello@ryvonx.com",
    generalEmail: "hello@ryvonx.com",
    phone: "+1 (555) 000-0000",
    whatsapp: "",
    officeAddress: "100 Financial District\nNew York, NY 10005",
    country: "United States",
    businessHours: "Mon–Fri, 9:00 AM – 6:00 PM EST",
    googleMapsUrl: "",
  },
  social: {
    facebook: "",
    instagram: "",
    twitter: "",
    linkedin: "",
    telegram: "",
    youtube: "",
    discord: "",
  },
  footer: {
    aboutText: APP_NAME,
    companyDescription:
      "A transparent, professionally managed pool trading fund. Verify performance before you invest.",
    copyrightText: `© ${new Date().getFullYear()} ${APP_NAME}. All rights reserved.`,
    disclaimerText:
      "Investing involves risk. Past performance does not guarantee future results.",
    logoUrl: "/images/logo.png",
    quickLinks: [
      { label: "Performance", href: ROUTES.performance },
      { label: "Recent Pool Trades", href: ROUTES.journal },
      { label: "Investors", href: ROUTES.investors },
      { label: "How It Works", href: ROUTES.howItWorks },
      { label: "FAQ", href: ROUTES.faq },
      { label: "Contact", href: ROUTES.contact },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" },
    ],
    newsletterTitle: "",
    newsletterDescription: "",
    ctaText: "",
    ctaLink: "",
  },
  sections: {
    hero: true,
    brokerCompatibility: true,
    featuredPoolManagers: true,
    performance: true,
    journal: true,
    recentActivity: true,
    statistics: true,
    howItWorks: true,
    whyRyvonx: true,
    testimonials: true,
    faq: true,
    contact: true,
    ctaBanner: false,
  },
  copy: {
    brokerCompatibility: {
      badge: "Broker Compatibility",
      title: "Trusted Brokerage Infrastructure",
      description:
        "RyvonX partners with verified brokers to enable secure trade execution, transparent capital management, and a seamless trading experience.",
      primaryPartnerLabel: "Primary Trading Partner",
    },
    featuredPoolManagers: {
      badge: "Top Performers",
      title: "Featured Pool Managers",
      description:
        "Top-ranked pool managers based on rating, capital under management, investor count, and trading consistency.",
    },
    performance: {
      badge: "Performance",
      title: "Pool Performance History",
      description:
        "Track the fund's growth over time. All data is updated in real-time and fully transparent.",
    },
    journal: {
      badge: "Recent Pool Trades",
      title: "Recent Pool Trades",
      description: "Recent published trades from pool managers across marketplace pools.",
      viewAllLabel: "View all recent trades",
    },
    recentActivity: {
      badge: "Live Activity",
      title: "Recent Investment Activity",
      description: "Real investment activity across the platform. Names are anonymized for privacy.",
      investmentsColumnTitle: "Recent Investments",
      payoutsColumnTitle: "Recent Payouts",
      viewAllLabel: "View all activity",
    },
    statistics: {
      badge: "Platform",
      title: "Live Platform Statistics",
      description: "Real-time metrics from the RyvonX marketplace — updated automatically.",
    },
    howItWorks: {
      badge: "How It Works",
      title: "Four Simple Steps",
      description:
        "From account creation to profit tracking — a straightforward investment process.",
    },
    whyRyvonx: {
      badge: "Why Ryvonx",
      title: "Built on Trust & Transparency",
      description:
        "Everything we do reinforces our core values: transparency, trust, professionalism, and long-term growth.",
    },
    testimonials: {
      badge: "Testimonials",
      title: "What Our Investors Say",
      description: "Hear from members of the Ryvonx community.",
    },
    faq: {
      badge: "FAQ",
      title: "Frequently Asked Questions",
      description: "Everything you need to know about investing with Ryvonx.",
      viewAllLabel: "View All FAQ",
    },
    contact: {
      badge: "Contact",
      title: "Get in Touch",
      description: "Have questions about Ryvonx? We'd love to hear from you.",
    },
    ctaBanner: {
      badge: "Get Started",
      title: "Ready to invest with transparency?",
      description: "Join verified pools managed by professional traders.",
      primaryButtonText: "Join Pool",
      primaryButtonLink: registerRoute(REGISTRATION_INTENTS.JOIN_POOL),
      secondaryButtonText: "Browse Marketplace",
      secondaryButtonLink: ROUTES.marketplace,
    },
  },
  howItWorksSteps: [
    {
      step: 1,
      icon: "Users",
      title: "Create Account",
      description: "Sign up in minutes with email verification. No complex onboarding.",
    },
    {
      step: 2,
      icon: "ArrowDownToLine",
      title: "Deposit Funds",
      description: "Transfer your investment amount. Minimum deposit starts at $100.",
    },
    {
      step: 3,
      icon: "Users",
      title: "Join the Pool",
      description: "Once approved, you receive proportional ownership in the trading pool.",
    },
    {
      step: 4,
      icon: "LineChart",
      title: "Track & Withdraw",
      description: "Monitor performance in real-time and request withdrawals anytime.",
    },
  ],
  whyRyvonxFeatures: [
    { id: "f1", icon: "Shield", title: "Verified Pool Managers", description: "Every pool manager passes rigorous verification before managing investor capital." },
    { id: "f2", icon: "BarChart3", title: "Transparent Trading", description: "Every closed trade is published with full details for complete transparency." },
    { id: "f3", icon: "LineChart", title: "Performance Tracking", description: "Real-time pool performance, ROI metrics, and historical data at your fingertips." },
    { id: "f4", icon: "Landmark", title: "Secure Marketplace", description: "Bank-grade encryption, Row Level Security, and a trusted investment environment." },
  ],
  seo: {
    title: APP_NAME,
    description:
      "RyvonX is a trusted marketplace where skilled traders manage investment pools and investors discover verified trading professionals.",
    keywords: "pool trading, investment pools, forex, trading fund, RyvonX",
    openGraphImageUrl: "/images/og-image.png",
    socialPreviewImageUrl: "/images/og-image.png",
    faviconUrl: "/favicon.ico",
  },
};
