import { defineEmailTemplate, baseVars, dashboardCta } from "./helpers";

/** Additional templates for Phase 5.5.3 automation (admin alerts, governance, etc.) */
export const AUTOMATION_TEMPLATES = [
  defineEmailTemplate({
    slug: "admin_platform_alert",
    name: "Admin Platform Alert",
    category: "system",
    description: "Generic admin alert for platform events.",
    subjectTemplate: "{{event_title}}",
    emailSpec: {
      title: "{{event_title}}",
      intro: "{{event_body}}",
      primaryAction: dashboardCta("Open Admin"),
    },
    variablesSchema: baseVars([
      { key: "event_title", label: "Title", sample: "New platform event" },
      { key: "event_body", label: "Body", sample: "Review required in the admin portal." },
    ]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "{{event_title}}",
    inAppBodyTemplate: "{{event_body}}",
  }),
  defineEmailTemplate({
    slug: "admin_new_deposit",
    name: "Admin — New Deposit",
    category: "system",
    description: "Alert admins when a deposit is submitted.",
    subjectTemplate: "New deposit — {{deposit_amount}}",
    emailSpec: {
      title: "New deposit submitted",
      intro: "An investor submitted a deposit of {{deposit_amount}} for review.",
      badge: { label: "Action Required", variant: "action_required" },
      blocks: [{ type: "info_card", label: "Reference", value: "{{transaction_id}}" }],
      primaryAction: { label: "Review Deposits", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([
      { key: "deposit_amount", label: "Amount", sample: "$5,000.00" },
      { key: "transaction_id", label: "Transaction ID", sample: "TXN-001" },
    ]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "New deposit submitted",
    inAppBodyTemplate: "Deposit of {{deposit_amount}} awaiting review.",
  }),
  defineEmailTemplate({
    slug: "admin_new_withdrawal",
    name: "Admin — New Withdrawal",
    category: "system",
    description: "Alert admins when a withdrawal is requested.",
    subjectTemplate: "New withdrawal — {{withdrawal_amount}}",
    emailSpec: {
      title: "New withdrawal request",
      intro: "An investor requested a withdrawal of {{withdrawal_amount}}.",
      badge: { label: "Action Required", variant: "action_required" },
      primaryAction: { label: "Review Withdrawals", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([
      { key: "withdrawal_amount", label: "Amount", sample: "$2,500.00" },
      { key: "transaction_id", label: "Transaction ID", sample: "TXN-002" },
    ]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "New withdrawal request",
    inAppBodyTemplate: "Withdrawal of {{withdrawal_amount}} awaiting review.",
  }),
  defineEmailTemplate({
    slug: "admin_new_pm_application",
    name: "Admin — PM Application",
    category: "pool_manager",
    description: "Alert admins of new pool manager application.",
    subjectTemplate: "New Pool Manager application",
    emailSpec: {
      title: "New Pool Manager application",
      intro: "{{manager_name}} submitted a Pool Manager application.",
      badge: { label: "Pending", variant: "pending" },
      primaryAction: dashboardCta("Review Application"),
    },
    variablesSchema: baseVars([{ key: "manager_name", label: "Applicant", sample: "Jordan Lee" }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "New PM application",
    inAppBodyTemplate: "{{manager_name}} submitted an application.",
  }),
  defineEmailTemplate({
    slug: "admin_support_ticket",
    name: "Admin — Support Ticket",
    category: "support",
    description: "Alert admins of new support ticket.",
    subjectTemplate: "New support ticket — {{support_ticket}}",
    emailSpec: {
      title: "New support ticket",
      intro: "A support ticket was opened: {{support_ticket}}",
      primaryAction: dashboardCta("Open Support Inbox"),
    },
    variablesSchema: baseVars([{ key: "support_ticket", label: "Subject", sample: "Deposit not showing" }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "New support ticket",
    inAppBodyTemplate: "{{support_ticket}}",
  }),
  defineEmailTemplate({
    slug: "admin_communication_failure",
    name: "Admin — Communication Failure",
    category: "system",
    description: "Alert admins when communication delivery fails.",
    subjectTemplate: "Communication delivery failed",
    emailSpec: {
      title: "Communication delivery failed",
      intro: "{{announcement_body}}",
      badge: { label: "Warning", variant: "warning" },
    },
    variablesSchema: baseVars([
      { key: "announcement_body", label: "Error", sample: "Email delivery failed after retries." },
    ]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "Communication delivery failed",
    inAppBodyTemplate: "{{announcement_body}}",
  }),
  defineEmailTemplate({
    slug: "governance_violation",
    name: "Governance Violation",
    category: "governance",
    description: "Governance rule violation on a pool.",
    subjectTemplate: "Governance violation — {{pool_name}}",
    emailSpec: {
      title: "Governance rule violation",
      intro: "A governance rule violation was recorded for {{pool_name}}.",
      badge: { label: "Warning", variant: "warning" },
      primaryAction: dashboardCta("View Pool"),
    },
    variablesSchema: baseVars([
      { key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" },
      { key: "review_notes", label: "Details", sample: "Drawdown limit exceeded." },
    ]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Governance violation",
    inAppBodyTemplate: "Violation recorded on {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "pool_restricted",
    name: "Pool Restricted",
    category: "governance",
    description: "Pool restrictions applied.",
    subjectTemplate: "{{pool_name}} — restrictions applied",
    emailSpec: {
      title: "Pool restrictions applied",
      intro: "Restrictions have been applied to {{pool_name}}.",
      badge: { label: "Suspended", variant: "suspended" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool restrictions applied",
    inAppBodyTemplate: "Restrictions applied to {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "pool_restored",
    name: "Pool Restored",
    category: "governance",
    description: "Pool returned to healthy status.",
    subjectTemplate: "{{pool_name}} — restored",
    emailSpec: {
      title: "Pool restored",
      intro: "{{pool_name}} has returned to healthy status.",
      badge: { label: "Healthy", variant: "healthy" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool restored",
    inAppBodyTemplate: "{{pool_name}} is healthy again.",
  }),
  defineEmailTemplate({
    slug: "governance_probation",
    name: "Governance Probation",
    category: "governance",
    description: "Pool placed on probation.",
    subjectTemplate: "{{pool_name}} — probation",
    emailSpec: {
      title: "Pool on probation",
      intro: "{{pool_name}} has been placed on probation.",
      badge: { label: "Warning", variant: "warning" },
      blocks: [{ type: "info_card", label: "Until", value: "{{maturity_date}}" }],
    },
    variablesSchema: baseVars([
      { key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" },
      { key: "maturity_date", label: "Probation end", sample: "Aug 1, 2026" },
    ]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool on probation",
    inAppBodyTemplate: "{{pool_name}} is on probation.",
  }),
  defineEmailTemplate({
    slug: "pool_proposal_submitted",
    name: "Pool Proposal Submitted",
    category: "pool_manager",
    description: "Pool submitted for RyvonX review.",
    subjectTemplate: "Pool submitted for review — {{pool_name}}",
    emailSpec: {
      title: "Pool submitted for review",
      intro: "Your pool {{pool_name}} has been submitted for RyvonX review.",
      badge: { label: "Under Review", variant: "under_review" },
      primaryAction: dashboardCta("View Pool"),
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool submitted",
    inAppBodyTemplate: "{{pool_name}} is under review.",
  }),
  defineEmailTemplate({
    slug: "pool_rejected",
    name: "Pool Rejected",
    category: "pool_manager",
    description: "Pool proposal rejected.",
    subjectTemplate: "Pool update — {{pool_name}}",
    emailSpec: {
      title: "Pool not approved",
      intro: "Your pool {{pool_name}} was not approved at this time.",
      badge: { label: "Rejected", variant: "rejected" },
      blocks: [{ type: "paragraph", text: "{{review_notes}}" }],
    },
    variablesSchema: baseVars([
      { key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" },
      { key: "review_notes", label: "Notes", sample: "Please revise strategy documentation." },
    ]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool not approved",
    inAppBodyTemplate: "{{pool_name}} was not approved.",
  }),
  defineEmailTemplate({
    slug: "pool_invitation",
    name: "Pool Invitation",
    category: "marketplace",
    description: "Investor invited to join a pool.",
    subjectTemplate: "You're invited to {{pool_name}}",
    emailSpec: {
      title: "Pool invitation",
      intro: "You have been invited to join {{pool_name}} on RyvonX.",
      primaryAction: { label: "Review Pool", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Pool invitation",
    inAppBodyTemplate: "Join {{pool_name}} when you're ready.",
  }),
  defineEmailTemplate({
    slug: "capital_review_scheduled",
    name: "Capital Review Scheduled",
    category: "capital_allocation",
    description: "Capital allocation review scheduled.",
    subjectTemplate: "Capital review scheduled — {{pool_name}}",
    emailSpec: {
      title: "Capital review scheduled",
      intro: "A capital allocation review has been scheduled for {{pool_name}}.",
      badge: { label: "Under Review", variant: "under_review" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Capital review scheduled",
    inAppBodyTemplate: "Review scheduled for {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "capital_allocation_increased",
    name: "Capital Allocation Increased",
    category: "capital_allocation",
    description: "RyvonX capital allocation increased.",
    subjectTemplate: "Capital increased — {{pool_name}}",
    emailSpec: {
      title: "Capital allocation increased",
      intro: "RyvonX capital allocation for {{pool_name}} has been increased.",
      badge: { label: "Approved", variant: "approved" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars([
      { key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" },
      { key: "investment_amount", label: "Amount", sample: "$250,000.00" },
    ]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Capital increased",
    inAppBodyTemplate: "Capital allocation increased for {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "capital_allocation_reduced",
    name: "Capital Allocation Reduced",
    category: "capital_allocation",
    description: "RyvonX capital allocation reduced.",
    subjectTemplate: "Capital reduced — {{pool_name}}",
    emailSpec: {
      title: "Capital allocation reduced",
      intro: "RyvonX capital allocation for {{pool_name}} has been reduced.",
      badge: { label: "Completed", variant: "completed" },
    },
    variablesSchema: baseVars([{ key: "pool_name", label: "Pool", sample: "Alpha Growth Pool" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Capital reduced",
    inAppBodyTemplate: "Capital allocation reduced for {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "challenge_enrollment",
    name: "Challenge Enrollment",
    category: "pool_manager",
    description: "Challenge payment received.",
    subjectTemplate: "Challenge payment received",
    emailSpec: {
      title: "Challenge payment received",
      intro: "Your challenge fee has been received. Our team will provision your evaluation account shortly.",
      primaryAction: dashboardCta("View Journey"),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Challenge payment received",
    inAppBodyTemplate: "Your challenge enrollment is being processed.",
  }),
  defineEmailTemplate({
    slug: "challenge_ready",
    name: "Challenge Account Ready",
    category: "pool_manager",
    description: "Challenge account credentials ready.",
    subjectTemplate: "Your challenge account is ready",
    emailSpec: {
      title: "Challenge account ready",
      intro: "Your trader evaluation account has been provisioned. Check your dashboard for credentials and rules.",
      badge: { label: "Verified", variant: "verified" },
      primaryAction: dashboardCta("Open Dashboard"),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Challenge account ready",
    inAppBodyTemplate: "Your evaluation account is ready.",
  }),
  defineEmailTemplate({
    slug: "manager_promotion",
    name: "Manager Promotion",
    category: "pool_manager",
    description: "Pool manager career promotion.",
    subjectTemplate: "Career promotion achieved",
    emailSpec: {
      title: "Career promotion achieved",
      intro: "Congratulations — you have been promoted to {{application_status}}.",
      badge: { label: "Approved", variant: "approved" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars([{ key: "application_status", label: "Level", sample: "Senior Manager" }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "Career promotion achieved",
    inAppBodyTemplate: "Promoted to {{application_status}}.",
  }),
  defineEmailTemplate({
    slug: "manager_achievement",
    name: "Manager Achievement",
    category: "pool_manager",
    description: "Achievement awarded to pool manager.",
    subjectTemplate: "Achievement awarded",
    emailSpec: {
      title: "Achievement awarded",
      intro: "You have been awarded: {{review_notes}}",
      badge: { label: "Completed", variant: "completed" },
    },
    variablesSchema: baseVars([{ key: "review_notes", label: "Achievement", sample: "Top Performer Q2" }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "Achievement awarded",
    inAppBodyTemplate: "{{review_notes}}",
  }),
  defineEmailTemplate({
    slug: "content_approved",
    name: "Content Approved",
    category: "pool_manager",
    description: "PM content approved for publication.",
    subjectTemplate: "Content approved",
    emailSpec: {
      title: "Content approved for publication",
      intro: "{{review_notes}}",
      badge: { label: "Approved", variant: "approved" },
    },
    variablesSchema: baseVars([{ key: "review_notes", label: "Content", sample: "Monthly pool update" }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "Content approved",
    inAppBodyTemplate: "{{review_notes}}",
  }),
  defineEmailTemplate({
    slug: "content_rejected",
    name: "Content Rejected",
    category: "pool_manager",
    description: "PM content not approved.",
    subjectTemplate: "Content not approved",
    emailSpec: {
      title: "Content not approved",
      intro: "{{review_notes}}",
      badge: { label: "Rejected", variant: "rejected" },
    },
    variablesSchema: baseVars([{ key: "review_notes", label: "Notes", sample: "Please revise tone and disclosures." }]),
    defaultChannels: ["in_app"],
    inAppTitleTemplate: "Content not approved",
    inAppBodyTemplate: "{{review_notes}}",
  }),
];
