import { defineEmailTemplate, baseVars, dashboardCta } from "./helpers";
import type { EmailCatalogEntry } from "./helpers";

const amountVars = [
  { key: "deposit_amount", label: "Deposit amount", sample: "$5,000.00" },
  { key: "investment_amount", label: "Investment amount", sample: "$10,000.00" },
  { key: "profit", label: "Profit", sample: "$357.14" },
  { key: "roi", label: "ROI", sample: "12.4%" },
  { key: "pool_name", label: "Pool name", sample: "Ryvonx Main Pool" },
  { key: "transaction_id", label: "Transaction ID", sample: "TXN-2026-00482" },
  { key: "maturity_date", label: "Maturity date", sample: "Oct 15, 2026" },
  { key: "investment_duration", label: "Duration", sample: "90 days" },
  { key: "current_balance", label: "Current balance", sample: "$15,357.14" },
];

export const INVESTMENT_TEMPLATES: EmailCatalogEntry[] = [
  defineEmailTemplate({
    slug: "deposit_submitted",
    name: "Deposit Submitted",
    category: "investment",
    description: "Crypto deposit submitted for review.",
    subjectTemplate: "Deposit received — {{deposit_amount}}",
    emailSpec: {
      title: "Deposit submitted",
      intro: "We received your deposit request. Our team will verify and credit your Funding Wallet once confirmed.",
      badge: { label: "Pending", variant: "pending" },
      blocks: [
        { type: "metric_row", items: [{ label: "Amount", value: "{{deposit_amount}}" }, { label: "Reference", value: "{{transaction_id}}" }] },
      ],
      primaryAction: dashboardCta("Track Deposit"),
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Deposit submitted",
    inAppBodyTemplate: "Your deposit of {{deposit_amount}} is pending review.",
  }),
  defineEmailTemplate({
    slug: "deposit_approved",
    name: "Deposit Approved",
    category: "investment",
    description: "Deposit approved and credited.",
    subjectTemplate: "Deposit approved — {{deposit_amount}}",
    emailSpec: {
      title: "Deposit approved",
      intro: "Your deposit has been verified and credited to your Funding Wallet.",
      badge: { label: "Approved", variant: "approved" },
      blocks: [
        { type: "info_card", label: "Amount credited", value: "{{deposit_amount}}" },
        { type: "info_card", label: "New balance", value: "{{current_balance}}" },
        { type: "info_card", label: "Reference", value: "{{transaction_id}}" },
      ],
      primaryAction: dashboardCta("View Wallet"),
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Deposit approved",
    inAppBodyTemplate: "{{deposit_amount}} credited to your Funding Wallet.",
  }),
  defineEmailTemplate({
    slug: "deposit_rejected",
    name: "Deposit Rejected",
    category: "investment",
    description: "Deposit could not be approved.",
    subjectTemplate: "Deposit could not be approved",
    emailSpec: {
      title: "Deposit not approved",
      intro: "Unfortunately we could not approve your recent deposit request.",
      badge: { label: "Rejected", variant: "rejected" },
      blocks: [
        { type: "info_card", label: "Amount", value: "{{deposit_amount}}" },
        { type: "alert", variant: "warning", text: "{{review_notes}}" },
      ],
      primaryAction: { label: "Contact Support", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([...amountVars, { key: "review_notes", label: "Review notes", sample: "Transaction hash could not be verified." }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "pool_investment_confirmed",
    name: "Investment Confirmed",
    category: "investment",
    description: "Pool investment confirmed.",
    subjectTemplate: "Investment confirmed — {{pool_name}}",
    emailSpec: {
      title: "Investment confirmed",
      intro: "Your capital is now actively managed in {{pool_name}}.",
      badge: { label: "Completed", variant: "completed" },
      blocks: [
        { type: "metric_row", items: [{ label: "Pool", value: "{{pool_name}}" }, { label: "Amount", value: "{{investment_amount}}" }] },
        { type: "info_card", label: "Maturity", value: "{{maturity_date}}" },
      ],
      primaryAction: { label: "Track Investment", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Investment confirmed",
    inAppBodyTemplate: "{{investment_amount}} invested in {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "investment_updated",
    name: "Investment Updated",
    category: "investment",
    description: "Investment allocation updated.",
    subjectTemplate: "Your investment in {{pool_name}} was updated",
    emailSpec: {
      title: "Investment updated",
      intro: "Your allocation in {{pool_name}} has been updated.",
      blocks: [{ type: "info_card", label: "Current invested", value: "{{investment_amount}}" }],
      primaryAction: { label: "Review Pool", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "investment_matured",
    name: "Investment Matured",
    category: "investment",
    description: "Pool term reached maturity.",
    subjectTemplate: "{{pool_name}} has reached maturity",
    emailSpec: {
      title: "Investment matured",
      intro: "Your investment in {{pool_name}} has reached its maturity date.",
      badge: { label: "Completed", variant: "completed" },
      blocks: [
        { type: "metric_row", items: [{ label: "Invested", value: "{{investment_amount}}" }, { label: "Profit", value: "{{profit}}" }] },
      ],
      primaryAction: dashboardCta("View Options"),
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "pool_profit_share",
    name: "Profit Distribution",
    category: "investment",
    description: "Trade profit recorded on allocation.",
    subjectTemplate: "Profit recorded in {{pool_name}}",
    emailSpec: {
      title: "Profit distribution",
      intro: "A trade in {{pool_name}} generated a profit on your allocation.",
      badge: { label: "Completed", variant: "completed" },
      blocks: [
        { type: "info_card", label: "Your share", value: "{{profit}}" },
        { type: "alert", variant: "info", text: "Transfer to your Funding Wallet or reinvest from your dashboard." },
      ],
      primaryAction: { label: "Manage Profit", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Profit updated",
    inAppBodyTemplate: "{{profit}} recorded in {{pool_name}}.",
  }),
  defineEmailTemplate({
    slug: "investment_summary",
    name: "Investment Summary",
    category: "investment",
    description: "Periodic investment summary.",
    subjectTemplate: "Your RyvonX investment summary",
    emailSpec: {
      title: "Investment summary",
      intro: "Here is a snapshot of your RyvonX portfolio performance.",
      blocks: [
        { type: "metric_row", items: [{ label: "Invested", value: "{{investment_amount}}" }, { label: "Profit", value: "{{profit}}" }, { label: "ROI", value: "{{roi}}" }] },
      ],
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "investment_closed",
    name: "Investment Closed",
    category: "investment",
    description: "Pool participation closed.",
    subjectTemplate: "Your participation in {{pool_name}} has closed",
    emailSpec: {
      title: "Investment closed",
      intro: "Your participation in {{pool_name}} has been closed.",
      badge: { label: "Completed", variant: "completed" },
      blocks: [{ type: "info_card", label: "Final value", value: "{{current_balance}}" }],
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars(amountVars),
    defaultChannels: ["email", "in_app"],
  }),
];
