import { defineEmailTemplate, baseVars, dashboardCta } from "./helpers";

const mktVars = [
  { key: "pool_name", label: "Pool name", sample: "Alpha Growth Pool" },
  { key: "manager_name", label: "Manager name", sample: "Jordan Lee" },
  { key: "roi", label: "ROI", sample: "18.2%" },
];

export const MARKETPLACE_TEMPLATES = [
  defineEmailTemplate({
    slug: "new_pool_available",
    name: "New Pool Available",
    category: "marketplace",
    description: "New pool listed.",
    subjectTemplate: "New pool on RyvonX — {{pool_name}}",
    emailSpec: {
      title: "New pool available",
      intro: "{{pool_name}} by {{manager_name}} is now available on the RyvonX marketplace.",
      primaryAction: { label: "Review Pool", urlKey: "dashboard_link" },
      showUnsubscribe: true,
    },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "pool_update",
    name: "Pool Update",
    category: "marketplace",
    description: "Pool profile updated.",
    subjectTemplate: "Update for {{pool_name}}",
    emailSpec: {
      title: "Pool update",
      intro: "There is a new update for {{pool_name}}.",
      primaryAction: { label: "View Pool", urlKey: "dashboard_link" },
      showUnsubscribe: true,
    },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "monthly_pool_performance",
    name: "Monthly Pool Performance",
    category: "marketplace",
    description: "Monthly performance digest.",
    subjectTemplate: "{{pool_name}} — monthly performance",
    emailSpec: {
      title: "Monthly performance",
      intro: "Performance summary for {{pool_name}}.",
      blocks: [{ type: "info_card", label: "Monthly ROI", value: "{{roi}}" }],
      primaryAction: { label: "View Performance", urlKey: "dashboard_link" },
      showUnsubscribe: true,
    },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "manager_announcement",
    name: "Manager Announcement",
    category: "marketplace",
    description: "Message from pool manager.",
    subjectTemplate: "Message from {{manager_name}}",
    emailSpec: { title: "Manager announcement", intro: "{{manager_name}} shared an update about {{pool_name}}.", primaryAction: { label: "Read Update", urlKey: "dashboard_link" } },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "featured_pool",
    name: "Featured Pool",
    category: "marketplace",
    description: "Featured pool highlight.",
    subjectTemplate: "Featured pool — {{pool_name}}",
    emailSpec: {
      title: "Featured pool",
      intro: "{{pool_name}} is featured on RyvonX this week.",
      primaryAction: { label: "Explore Pool", urlKey: "dashboard_link" },
      showUnsubscribe: true,
    },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "pool_recommendation",
    name: "Pool Recommendation",
    category: "marketplace",
    description: "Personalized pool recommendation.",
    subjectTemplate: "Recommended for you — {{pool_name}}",
    emailSpec: {
      title: "Pool recommendation",
      intro: "Based on your portfolio, you may be interested in {{pool_name}}.",
      primaryAction: { label: "View Pool", urlKey: "dashboard_link" },
      showUnsubscribe: true,
    },
    variablesSchema: baseVars(mktVars),
    defaultChannels: ["email"],
  }),
];

export const STATEMENT_TEMPLATES = [
  defineEmailTemplate({
    slug: "monthly_statement",
    name: "Monthly Statement",
    category: "reports",
    description: "Monthly account statement.",
    subjectTemplate: "Your RyvonX monthly statement",
    emailSpec: {
      title: "Monthly statement",
      intro: "Your monthly statement is ready to view and download.",
      primaryAction: { label: "Download Report", urlKey: "dashboard_link" },
      secondaryAction: { label: "View Statement", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([{ key: "statement_period", label: "Period", sample: "June 2026" }]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "quarterly_statement",
    name: "Quarterly Statement",
    category: "reports",
    description: "Quarterly statement.",
    subjectTemplate: "Your RyvonX quarterly statement",
    emailSpec: { title: "Quarterly statement", intro: "Your quarterly statement is available.", primaryAction: { label: "Download Report", urlKey: "dashboard_link" } },
    variablesSchema: baseVars([{ key: "statement_period", label: "Period", sample: "Q2 2026" }]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "annual_statement",
    name: "Annual Statement",
    category: "reports",
    description: "Annual statement.",
    subjectTemplate: "Your RyvonX annual statement",
    emailSpec: { title: "Annual statement", intro: "Your annual investment statement is ready.", primaryAction: { label: "Download Report", urlKey: "dashboard_link" } },
    variablesSchema: baseVars([{ key: "statement_period", label: "Period", sample: "2026" }]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "performance_report",
    name: "Performance Report",
    category: "reports",
    description: "Performance report.",
    subjectTemplate: "Your RyvonX performance report",
    emailSpec: {
      title: "Performance report",
      intro: "Your performance report is ready.",
      blocks: [{ type: "metric_row", items: [{ label: "ROI", value: "{{roi}}" }, { label: "Profit", value: "{{profit}}" }] }],
      primaryAction: { label: "Download Report", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([{ key: "profit", label: "Profit", sample: "$4,820.00" }, { key: "roi", label: "ROI", sample: "14.2%" }]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "tax_summary",
    name: "Tax Summary",
    category: "reports",
    description: "Annual tax summary (future).",
    subjectTemplate: "Your RyvonX tax summary — {{statement_period}}",
    emailSpec: {
      title: "Tax summary",
      intro: "Your tax summary for {{statement_period}} will be available for download.",
      blocks: [{ type: "alert", variant: "info", text: "Tax documents are provided for informational purposes. Consult your tax advisor." }],
      primaryAction: { label: "Download Report", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([{ key: "statement_period", label: "Tax year", sample: "2026" }]),
    defaultChannels: ["email"],
  }),
];

export const SUPPORT_TEMPLATES = [
  defineEmailTemplate({
    slug: "support_ticket_created",
    name: "Support Ticket Created",
    category: "support",
    description: "Ticket opened.",
    subjectTemplate: "Support ticket received — {{support_ticket}}",
    emailSpec: {
      title: "Support ticket created",
      intro: "We received your support request and will respond shortly.",
      badge: { label: "Pending", variant: "pending" },
      blocks: [{ type: "info_card", label: "Subject", value: "{{support_ticket}}" }],
      primaryAction: dashboardCta("View Ticket"),
    },
    variablesSchema: baseVars([{ key: "support_ticket", label: "Ticket subject", sample: "Deposit not showing" }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "support_reply",
    name: "Support Reply",
    category: "support",
    description: "Admin replied to ticket.",
    subjectTemplate: "Re: {{support_ticket}}",
    emailSpec: {
      title: "Support reply",
      intro: "Our support team has replied to your ticket.",
      blocks: [{ type: "paragraph", text: "{{reply_preview}}" }],
      primaryAction: dashboardCta("View Conversation"),
    },
    variablesSchema: baseVars([
      { key: "support_ticket", label: "Ticket subject", sample: "Deposit not showing" },
      { key: "reply_preview", label: "Reply preview", sample: "We located your deposit and it is being processed." },
    ]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Support reply",
    inAppBodyTemplate: "Our team replied to: {{support_ticket}}",
  }),
  defineEmailTemplate({
    slug: "support_escalated",
    name: "Support Escalated",
    category: "support",
    description: "Ticket escalated.",
    subjectTemplate: "Your support ticket was escalated",
    emailSpec: { title: "Ticket escalated", intro: "Your ticket has been escalated to a senior specialist.", badge: { label: "Under Review", variant: "under_review" }, primaryAction: dashboardCta() },
    variablesSchema: baseVars([{ key: "support_ticket", label: "Ticket", sample: "Deposit not showing" }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "support_resolved",
    name: "Support Resolved",
    category: "support",
    description: "Ticket resolved.",
    subjectTemplate: "Support ticket resolved",
    emailSpec: { title: "Ticket resolved", intro: "Your support ticket has been marked as resolved.", badge: { label: "Completed", variant: "completed" }, primaryAction: dashboardCta() },
    variablesSchema: baseVars([{ key: "support_ticket", label: "Ticket", sample: "Deposit not showing" }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "support_closed",
    name: "Support Ticket Closed",
    category: "support",
    description: "Ticket closed.",
    subjectTemplate: "Support ticket closed — {{support_ticket}}",
    emailSpec: {
      title: "Ticket closed",
      intro: "Your support ticket has been closed. Reply to reopen if you need further assistance.",
      badge: { label: "Closed", variant: "completed" },
      primaryAction: dashboardCta("View Support"),
    },
    variablesSchema: baseVars([{ key: "support_ticket", label: "Ticket", sample: "Deposit not showing" }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Support ticket closed",
    inAppBodyTemplate: "{{support_ticket}} has been closed.",
  }),
  defineEmailTemplate({
    slug: "support_satisfaction",
    name: "Customer Satisfaction Request",
    category: "support",
    description: "CSAT survey.",
    subjectTemplate: "How was your support experience?",
    emailSpec: { title: "We value your feedback", intro: "Please tell us about your recent support experience.", primaryAction: { label: "Share Feedback", urlKey: "dashboard_link" } },
    variablesSchema: baseVars(),
    defaultChannels: ["email"],
  }),
];

export const PLATFORM_TEMPLATES = [
  defineEmailTemplate({
    slug: "maintenance_notice",
    name: "Maintenance Notice",
    category: "announcements",
    description: "Scheduled maintenance.",
    subjectTemplate: "RyvonX scheduled maintenance",
    emailSpec: {
      title: "Scheduled maintenance",
      intro: "RyvonX will undergo scheduled maintenance.",
      blocks: [{ type: "alert", variant: "info", text: "{{announcement_body}}" }],
    },
    variablesSchema: baseVars([{ key: "announcement_body", label: "Details", sample: "Saturday 2–4 AM UTC. Dashboard access may be limited." }]),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Scheduled maintenance",
    inAppBodyTemplate: "{{announcement_body}}",
  }),
  defineEmailTemplate({
    slug: "announcement_broadcast",
    name: "Platform Announcement",
    category: "announcements",
    description: "General announcement.",
    subjectTemplate: "{{announcement_title}}",
    emailSpec: {
      title: "{{announcement_title}}",
      intro: "{{announcement_preview}}",
      blocks: [{ type: "paragraph", text: "{{announcement_body}}" }],
      showUnsubscribe: true,
    },
    variablesSchema: baseVars([
      { key: "announcement_title", label: "Title", sample: "Platform update" },
      { key: "announcement_preview", label: "Preview", sample: "New marketplace features are live." },
      { key: "announcement_body", label: "Body", sample: "We have released enhanced pool analytics and reporting." },
    ]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "feature_release",
    name: "Feature Release",
    category: "announcements",
    description: "New feature launch.",
    subjectTemplate: "New on RyvonX — {{announcement_title}}",
    emailSpec: {
      title: "New feature",
      intro: "{{announcement_body}}",
      primaryAction: dashboardCta("Explore Feature"),
      showUnsubscribe: true,
    },
    variablesSchema: baseVars([
      { key: "announcement_title", label: "Feature name", sample: "Pool Profit Controls" },
      { key: "announcement_body", label: "Description", sample: "Transfer or reinvest pool profit directly from your dashboard." },
    ]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "scheduled_downtime",
    name: "Scheduled Downtime",
    category: "announcements",
    description: "Scheduled downtime window.",
    subjectTemplate: "RyvonX scheduled downtime",
    emailSpec: {
      title: "Scheduled downtime",
      intro: "RyvonX will be temporarily unavailable during the following window.",
      blocks: [{ type: "alert", variant: "warning", text: "{{announcement_body}}" }],
    },
    variablesSchema: baseVars([{ key: "announcement_body", label: "Window", sample: "Saturday 2–4 AM UTC." }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "platform_update",
    name: "Platform Update",
    category: "announcements",
    description: "General platform update.",
    subjectTemplate: "RyvonX platform update",
    emailSpec: {
      title: "Platform update",
      intro: "{{announcement_preview}}",
      blocks: [{ type: "paragraph", text: "{{announcement_body}}" }],
      primaryAction: dashboardCta("View Dashboard"),
    },
    variablesSchema: baseVars([
      { key: "announcement_preview", label: "Preview", sample: "We've improved performance and reliability." },
      { key: "announcement_body", label: "Details", sample: "Dashboard load times are faster and reporting is more accurate." },
    ]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "security_notice",
    name: "Security Notice",
    category: "security",
    description: "Platform security notice.",
    subjectTemplate: "Important security notice from RyvonX",
    emailSpec: { title: "Security notice", intro: "{{announcement_body}}", badge: { label: "Action Required", variant: "action_required" }, primaryAction: dashboardCta() },
    variablesSchema: baseVars([{ key: "announcement_body", label: "Notice", sample: "Please review recent account activity." }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "emergency_announcement",
    name: "Emergency Announcement",
    category: "announcements",
    description: "Urgent platform notice.",
    subjectTemplate: "Important RyvonX announcement",
    emailSpec: { title: "Important notice", intro: "{{announcement_body}}", badge: { label: "Warning", variant: "warning" } },
    variablesSchema: baseVars([{ key: "announcement_body", label: "Message", sample: "Emergency maintenance in progress." }]),
    defaultChannels: ["email", "in_app"],
  }),
];
