import { defineEmailTemplate, baseVars, dashboardCta } from "./helpers";
import type { EmailCatalogEntry } from "./helpers";

const SYSTEM_TEMPLATES: EmailCatalogEntry[] = [
  defineEmailTemplate({
    slug: "welcome",
    name: "Welcome",
    category: "system",
    description: "Welcome email for new investors.",
    subjectTemplate: "Welcome to RyvonX, {{first_name}}",
    emailSpec: {
      title: "Welcome to RyvonX",
      intro: "Your account is ready. RyvonX gives you transparent access to professionally managed trading pools with full visibility into performance.",
      badge: { label: "Verified", variant: "verified" },
      blocks: [
        { type: "paragraph", text: "Explore the marketplace, fund your wallet, and invest with confidence." },
      ],
      primaryAction: dashboardCta("Explore Dashboard"),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
    inAppTitleTemplate: "Welcome to RyvonX",
    inAppBodyTemplate: "Your account is ready. Explore the marketplace and start investing.",
  }),
  defineEmailTemplate({
    slug: "email_verification",
    name: "Email Verification",
    category: "system",
    description: "Verify email address.",
    subjectTemplate: "Verify your RyvonX email",
    emailSpec: {
      title: "Verify your email",
      intro: "Please confirm your email address to secure your RyvonX account.",
      blocks: [{ type: "alert", variant: "info", text: "This link expires in 24 hours for your security." }],
      primaryAction: { label: "Verify Email", urlKey: "verification_link" },
    },
    variablesSchema: baseVars([
      { key: "verification_link", label: "Verification link", sample: "https://ryvonx.com/verify-email?token=..." },
    ]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "security_password_reset",
    name: "Password Reset",
    category: "security",
    description: "Password reset request.",
    subjectTemplate: "Reset your RyvonX password",
    emailSpec: {
      title: "Reset your password",
      intro: "We received a request to reset your password. If you made this request, use the button below.",
      blocks: [
        { type: "alert", variant: "warning", text: "If you did not request a password reset, you can safely ignore this email." },
      ],
      primaryAction: { label: "Reset Password", urlKey: "verification_link" },
      showSupport: true,
    },
    variablesSchema: baseVars([
      { key: "verification_link", label: "Reset link", sample: "https://ryvonx.com/reset-password?token=..." },
    ]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "password_changed",
    name: "Password Changed",
    category: "security",
    description: "Confirmation after password change.",
    subjectTemplate: "Your RyvonX password was changed",
    emailSpec: {
      title: "Password updated",
      intro: "Your RyvonX account password was successfully changed.",
      badge: { label: "Completed", variant: "completed" },
      blocks: [{ type: "alert", variant: "info", text: "If you did not make this change, contact support immediately." }],
      primaryAction: { label: "Contact Support", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "login_alert",
    name: "Login Alert",
    category: "security",
    description: "New login detected.",
    subjectTemplate: "New sign-in to your RyvonX account",
    emailSpec: {
      title: "New sign-in detected",
      intro: "We noticed a new sign-in to your RyvonX account.",
      blocks: [
        { type: "info_card", label: "Time", value: "{{login_time}}" },
        { type: "info_card", label: "Location", value: "{{login_location}}" },
        { type: "info_card", label: "Device", value: "{{login_device}}" },
      ],
      primaryAction: dashboardCta("Review Account"),
    },
    variablesSchema: baseVars([
      { key: "login_time", label: "Login time", sample: "Jul 16, 2026 · 9:41 AM UTC" },
      { key: "login_location", label: "Location", sample: "London, UK" },
      { key: "login_device", label: "Device", sample: "Chrome on Windows" },
    ]),
    defaultChannels: ["email"],
  }),
  defineEmailTemplate({
    slug: "security_alert",
    name: "Security Alert",
    category: "security",
    description: "General security alert.",
    subjectTemplate: "Security alert for your RyvonX account",
    emailSpec: {
      title: "Security alert",
      intro: "We detected activity that requires your attention.",
      badge: { label: "Action Required", variant: "action_required" },
      blocks: [{ type: "paragraph", text: "{{alert_message}}" }],
      primaryAction: dashboardCta("Secure Account"),
    },
    variablesSchema: baseVars([{ key: "alert_message", label: "Alert message", sample: "Unusual withdrawal attempt blocked." }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "profile_updated",
    name: "Profile Updated",
    category: "system",
    description: "Profile settings changed.",
    subjectTemplate: "Your RyvonX profile was updated",
    emailSpec: {
      title: "Profile updated",
      intro: "Your account profile information was successfully updated.",
      badge: { label: "Completed", variant: "completed" },
      primaryAction: dashboardCta("View Settings"),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "account_verified",
    name: "Account Verified",
    category: "system",
    description: "Account verification complete.",
    subjectTemplate: "Your RyvonX account is verified",
    emailSpec: {
      title: "Account verified",
      intro: "Your identity verification is complete. You now have full access to RyvonX investment features.",
      badge: { label: "Verified", variant: "verified" },
      primaryAction: dashboardCta("Start Investing"),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "account_suspended",
    name: "Account Suspended",
    category: "system",
    description: "Account suspended notification.",
    subjectTemplate: "Your RyvonX account has been suspended",
    emailSpec: {
      title: "Account suspended",
      intro: "Your RyvonX account has been temporarily suspended pending review.",
      badge: { label: "Suspended", variant: "suspended" },
      blocks: [{ type: "paragraph", text: "{{review_notes}}" }],
      primaryAction: { label: "Contact Support", urlKey: "dashboard_link" },
    },
    variablesSchema: baseVars([{ key: "review_notes", label: "Review notes", sample: "Please contact support to resolve compliance items." }]),
    defaultChannels: ["email", "in_app"],
  }),
  defineEmailTemplate({
    slug: "account_reactivated",
    name: "Account Reactivated",
    category: "system",
    description: "Account reactivated.",
    subjectTemplate: "Your RyvonX account is active again",
    emailSpec: {
      title: "Account reactivated",
      intro: "Your RyvonX account has been reactivated. Welcome back.",
      badge: { label: "Verified", variant: "verified" },
      primaryAction: dashboardCta(),
    },
    variablesSchema: baseVars(),
    defaultChannels: ["email", "in_app"],
  }),
];

export { SYSTEM_TEMPLATES };
